name: PuneVaccine

on:
  push:
    paths:
      - .github/workflows/pune-vaccine.yml # Only run a new workflow every time this file (pune-vaccine.yaml) file changes
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *' # Run this workflow every 1 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Fetch data 
        uses: githubocto/flat@v2
        with:
          http_url: https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=363&date=20-05-2021 # The data to fetch every 5 minutes
          downloaded_filename: pune-vaccine.json
